apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Pull down the foundation blueprints automatically
resources:
  - ../../base

# Explicitly tracking image tag patches natively via Kustomize CLI engine
images:
  - name: ghcr.io/amarpal-singh5/kubernetes-gitops-platform
    newTag: latest
